<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.5.1" />
    <PackageReference Include="Syncfusion.Blazor.Charts" Version="29.1.35" />
    <PackageReference Include="Syncfusion.Blazor.Core" Version="29.1.35" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="29.1.35" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="29.1.35" />
  </ItemGroup>
</Project>